default: home
variants:
- name: home
  context:
    title: "2015"
    content: |
      <cite>24 ways</cite> is the advent calendar for web geeks. Each day throughout December we publish a daily dose of web design and development goodness to bring you all a little Christmas cheer. [Learn more](/about)
    config:
      mods: [summaries, inset]
      component: summary
      reversed: true
      items: ["@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown"]
- name: topic
  context:
    title: "Business"
    titleIcon: topic-business
    content: |
      Where there's muck, there are clients, deliverables and contracts. Occasionally, there's brass. Here are articles on developing and improving relationships with clients; writing contracts and presenting your work; and encouraging success and avoiding failure.
    results: true
    items: ["@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary", "@summary","@summary","@summary","@summary","@summary","@summary","@summary", "@summary","@summary","@summary"]
    section: topics
    traverse:
      type: topic
      next:
        url: /topics/code/
        title: "Code"
- name: archive
  context:
    title: "2013"
    content: |
      Scourge of browser vendors everywhere, WaSP buzzed its last in March. Dave Shea's CSS Zen Garden celebrated its tenth anniversary in May, and Google Glass was released. Ever broad in its interests, 24 ways tamed Grunt, URLs and GitHub Pages, encouraged readers to write and publish books, and leavened all that with goodies on project management, web typography and SVG.
    section: archives
    theme: year-2013
    traverse:
      type: archive
      prev:
        url: /2012/
        title: "2012"
      next:
        url: /2014/
        title: "2014"
    config:
      mods: [summaries, inset]
      component: summary
      items:
        ["@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown","@summary--countdown"]
- name: author
  context:
    title: "Rachel Andrew"
    section: authors
    avatar:
      src: https://cloud.24ways.org/authors/rachelandrew280.jpg
      size: 280
    content: |
      <span class="fn n">Rachel Andrew</span> is a Director of edgeofmyseat.com, a UK web development consultancy and creators of the small content management system, [Perch](https://grabaperch.com/). She is the author of a number of [books](https://rachelandrew.co.uk/books), and is a regular columnist for [A List Apart](http://alistapart.com/author/rachelandrew).

      She curates a popular [email newsletter on CSS Layout](http://csslayout.news/), and will be launching a [CSS Layout online workshop](https://thecssworkshop.com/) in early 2016.

      When not writing about business and technology on her blog at [rachelandrew.co.uk](https://rachelandrew.co.uk) or [speaking at conferences](http://lanyrd.com/profile/rachelandrew/), you will usually find Rachel running up and down one of the giant hills in Bristol.

      <span class="caption">Photo: [James Duncan Davidson](http://duncandavidson.com/)</span>
    traverse:
      type: author
      prev:
        url: /authors/johnallsopp/
        title: "John Allsopp"
      next:
        url: /authors/paulannett/
        title: "Paul Annett"
- name: search-results
  context:
    title: "Search results for ‘design systems’"
    results: true
    config:
      mods: [summaries, inset]
      component: summary
      items: ["@summary--short","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary","@summary", "@summary","@summary"]
