context:
  prism: true
  title: "Starting Your HTML5 Project on the Right Foot (and Keeping It There)"
  description: "Drew McLellan brings our 2015 calendar to a motivational close with some encouragement for the year ahead. Year’s end is a time for reflection and finding new purpose and enthusiasm for what we do. By tackling the thorniest design and development problems, we can make the greatest impact – and have the most fun. Merry Christmas and a happy New Year!"
  url: https://24ways.org/2015/starting-on-the-right-foot/
  author: Drew McLellan
  handle: drewm
  avatar:
    size: 160
    src: https://cloud.24ways.org/authors/drewmclellan280.jpg
  section: article
  theme: year-2013
  traverse:
    type: article
    prev:
      url: /2015/how-tabs-should-work/
      title: "How Tabs Should Work"
    next:
      url: /2015/solve-the-hard-problems/
      title: "Solve the Hard Problems"
  related: true
  comments:
  - "@comment"
  - "@comment--unhelpful"
